python3 run_sem_withdev.py \
  --bert_model bert-base-uncased \
  --do_train \
  --do_eval \
  --gradient_accumulation_steps 8 \
  --train_batch_size 64 \
  --eval_batch_size 32 \
  --dev_batch_size 8 \
  --num_train_epochs 50.0 \
  --max_seq_length 128 \
  --learning_rate 6e-5 \
  --output_dir output_path_my111np65 \
  --log_dir log_path_my111np65
python3 run_sem_withdev.py \
  --bert_model bert-base-uncased \
  --do_train \
  --do_eval \
  --gradient_accumulation_steps 8 \
  --train_batch_size 64 \
  --eval_batch_size 32 \
  --dev_batch_size 8 \
  --num_train_epochs 50.0 \
  --max_seq_length 128 \
  --learning_rate 8e-5 \
  --output_dir output_path_my111np85 \
  --log_dir log_path_my111np85
python3 run_sem_withdev.py \
  --bert_model bert-base-uncased \
  --do_train \
  --do_eval \
  --gradient_accumulation_steps 8 \
  --train_batch_size 64 \
  --eval_batch_size 32 \
  --dev_batch_size 8 \
  --num_train_epochs 50.0 \
  --max_seq_length 128 \
  --learning_rate 1e-4 \
  --output_dir output_path_my111np14 \
  --log_dir log_path_my111np14
python3 run_sem_withdev.py \
  --bert_model bert-base-uncased \
  --do_train \
  --do_eval \
  --gradient_accumulation_steps 8 \
  --train_batch_size 64 \
  --eval_batch_size 32 \
  --dev_batch_size 8 \
  --num_train_epochs 50.0 \
  --max_seq_length 128 \
  --learning_rate 1e-3 \
  --output_dir output_path_my111np13 \
  --log_dir log_path_my111np13
python3 run_sem_withdev.py \
  --bert_model bert-base-uncased \
  --do_train \
  --do_eval \
  --gradient_accumulation_steps 8 \
  --train_batch_size 64 \
  --eval_batch_size 32 \
  --dev_batch_size 8 \
  --num_train_epochs 50.0 \
  --max_seq_length 128 \
  --learning_rate 1e-6 \
  --output_dir output_path_my111np16 \
  --log_dir log_path_my111np16
python3 run_sem_withdev.py \
  --bert_model bert-base-uncased \
  --do_train \
  --do_eval \
  --gradient_accumulation_steps 8 \
  --train_batch_size 64 \
  --eval_batch_size 32 \
  --dev_batch_size 8 \
  --num_train_epochs 50.0 \
  --max_seq_length 128 \
  --learning_rate 5e-4 \
  --output_dir output_path_my111np54 \
  --log_dir log_path_my111np54
python3 run_sem_withdev.py \
  --bert_model bert-base-uncased \
  --do_train \
  --do_eval \
  --gradient_accumulation_steps 8 \
  --train_batch_size 64 \
  --eval_batch_size 32 \
  --dev_batch_size 8 \
  --num_train_epochs 50.0 \
  --max_seq_length 128 \
  --learning_rate 5e-3 \
  --output_dir output_path_my111np53 \
  --log_dir log_path_my111np53
python3 run_sem_withdev.py \
  --bert_model bert-base-uncased \
  --do_train \
  --do_eval \
  --gradient_accumulation_steps 8 \
  --train_batch_size 64 \
  --eval_batch_size 32 \
  --dev_batch_size 8 \
  --num_train_epochs 50.0 \
  --max_seq_length 128 \
  --learning_rate 5e-6 \
  --output_dir output_path_my111np56 \
  --log_dir log_path_my111np56